#!/bin/bash

### BEGIN INIT INFO
# Provides:          varnish-bans-manager-celeryd
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Varnish Bans Manager (VBM) Celery worker daemon
### END INIT INFO

##
## Configuration.
##
VIRTUALENV="/var/www/varnish-bans-manager"
CELERYD_MULTI="varnish-bans-manager celeryd_multi"
CELERYD_CTL="varnish-bans-manager celeryctl"
CELERYD_PID_FILE="/var/run/varnish-bans-manager/celeryd.pid"
CELERYD_LOG_FILE="/var/log/varnish-bans-manager/celeryd.log"
CELERYD_LOG_LEVEL="WARNING"
CELERYD_CMD="-m celery.bin.celeryd_detach"
CELERYD_NODES="w1"
CELERYD_DAEMON_OPTS="\
    --pidfile="$CELERYD_PID_FILE" \
    --logfile="$CELERYD_LOG_FILE" \
    --loglevel="$CELERYD_LOG_LEVEL" \
    --uid=www-data \
    --gid=www-data \
    --time-limit=300 \
    --concurrency=2"

##
##
##
start_workers () {
    $CELERYD_MULTI start $CELERYD_NODES $CELERYD_DAEMON_OPTS --cmd="$CELERYD_CMD"
}

##
##
##
restart_workers () {
    $CELERYD_MULTI restart $CELERYD_NODES $CELERYD_DAEMON_OPTS --cmd="$CELERYD_CMD"
}

##
##
##
stop_workers () {
    $CELERYD_MULTI stop $CELERYD_NODES --pidfile="$CELERYD_PID_FILE"
}

##
##
##
source "$VIRTUALENV/bin/activate"

##
##
##
case "$1" in
    start)
        start_workers
    ;;

    stop)
        stop_workers
    ;;

    reload|force-reload)
        echo "Use restart"
    ;;

    status)
        $CELERYD_CTL status $CELERYD_CTL_OPTS
    ;;

    restart)
        restart_workers
    ;;

    try-restart)
        restart_workers
    ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}" 1>&2
        exit 64  # EX_USAGE
    ;;
esac

##
## Done!
##
deactivate
exit 0
