#!/bin/bash

### BEGIN INIT INFO
# Provides:          varnish-bans-manager-celeryd
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Varnish Bans Manager (VBM) Celery worker daemon
### END INIT INFO

##
## Configuration.
##
CELERYD_VIRTUALENV="/var/www/varnish-bans-manager"
CELERYD_MULTI="python -mvarnish_bans_manager.runner celeryd_multi"
CELERYD_CTL="python -mvarnish_bans_manager.runner celeryctl"
CELERYD_USER="www-data"
CELERYD_GROUP="www-data"
CELERYD_PID_DIR="/var/run/varnish-bans-manager"
CELERYD_PID_FILE="$CELERYD_PID_DIR/celeryd.pid"
CELERYD_LOG_DIR="/var/log/varnish-bans-manager"
CELERYD_LOG_FILE="$CELERYD_LOG_DIR/celeryd.log"
CELERYD_LOG_LEVEL="WARNING"
CELERYD_NODES="w1"
CELERYD_DAEMON_OPTS="\
    --pidfile="$CELERYD_PID_FILE" \
    --uid="$CELERYD_USER" \
    --gid="$CELERYD_GROUP" \
    --logfile="$CELERYD_LOG_FILE" \
    --loglevel="$CELERYD_LOG_LEVEL" \
    --cmd=-mcelery.bin.celeryd_detach \
    --time-limit=300 \
    --concurrency=2"

##
##
##
start_celeryd () {
    echo "Starting celeryd..."
    $CELERYD start $CELERYD_NODES --app=apw $CELERYD_DAEMON_OPTS
}

##
##
##
stop_celeryd () {
    echo "Stopping celeryd..."
    $CELERYD_MULTI stop $CELERYD_NODES --app=apw --pidfile="$CELERYD_PID_FILE"
    rm -f "$CELERYD_PID_FILE"
}

##
##
##
restart_celeryd () {
    echo "Restarting celeryd..."
    $CELERYD_MULTI restart $CELERYD_NODES --app=apw $CELERYD_DAEMON_OPTS
}

##
##
##
status_celeryd () {
    $CELERYD_CTL status $CELERYD_CTL_OPTS
}

##
##
##
source "$CELERYD_VIRTUALENV/bin/activate"
mkdir -p "$CELERYD_PID_DIR" "$CELERYD_LOG_DIR"
chown $CELERYD_USER:$CELERYD_GROUP "$CELERYD_PID_DIR" "$CELERYD_LOG_DIR"

##
##
##
case "$1" in
    start)
        start_celeryd
    ;;

    stop)
        stop_celeryd
    ;;

    restart)
        restart_celeryd
    ;;

    reload|force-reload)
        echo "Use restart" 1>&2
        exit 1
    ;;

    status)
        status_celeryd
    ;;

    *)
        echo "Usage: $0 {start|stop|restart|status}" 1>&2
        exit 64  # EX_USAGE
    ;;
esac

##
## Done!
##
deactivate
exit 0
